INSERT INTO radios (nombre, genero, url_stream, imagen_url, favorita) VALUES
('Absolute Rock', 'Rock', 'https://stream.absoluterock.com/stream', NULL, false),
('Rock FM', 'Rock', 'https://rockfm.stream/rock', NULL, false),
('Kerrang Radio', 'Rock', 'https://kerrang.stream/radio', NULL, false),
('Triple M', 'Rock', 'https://triplem.stream/rock', NULL, false),
('Lofi Girl', 'Lo-Fi', 'https://lofi.stream/girl', NULL, false),
('Chillhop', 'Lo-Fi', 'https://chillhop.stream/radio', NULL, false),
('ChilledCow', 'Lo-Fi', 'https://chilledcow.stream/lofi', NULL, false),
('Radio Lofi', 'Lo-Fi', 'https://radiolofi.stream/stream', NULL, false),
('Hits Radio', 'Pop', 'https://hitsradio.stream/pop', NULL, false),
('Capital FM', 'Pop', 'https://capitalfm.stream/radio', NULL, false),
('Los 40', 'Pop', 'https://los40.stream/radio', NULL, false),
('NRJ', 'Pop', 'https://nrj.stream/pop', NULL, false),
('Jazz FM', 'Jazz', 'https://jazzfm.stream/radio', NULL, false),
('Jazz24', 'Jazz', 'https://jazz24.stream/stream', NULL, false),
('SomaFM Groove Salad', 'Jazz', 'https://somafm.stream/groovesalad', NULL, false),
('DI.FM', 'Electronic', 'https://difm.stream/electronic', NULL, false),
('SomaFM Digital', 'Electronic', 'https://somafm.stream/digital', NULL, false),
('Digitally Imported', 'Electronic', 'https://di.stream/radio', NULL, false),
('Urbana', 'Latino', 'https://urbana.stream/radio', NULL, false),
('Exa FM', 'Latino', 'https://exafm.stream/radio', NULL, false),
('Zona Latina', 'Latino', 'https://zonalatina.stream/radio', NULL, false),
('Mega FM', 'Latino', 'https://megafm.stream/radio', NULL, false),
('Calm Radio Classical', 'Classical', 'https://calmradio.stream/classical', NULL, false),
('WQXR', 'Classical', 'https://wqxr.stream/classical', NULL, false),
('Classic FM', 'Classical', 'https://classicfm.stream/radio', NULL, false);
